# Generated by Django 4.2.9 on 2024-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
