# Generated by Django 4.2.9 on 2024-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0004_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
